### PR TITLE
Use DBItest for testing

### PR DESCRIPTION
**Pull request by krlmlr**
Currently calls `test_all()`: this may or may not be desired.

### CODE REVIEW

**Comment by krlmlr** [comment]
Includes infrastructure, removes some minor bugs, removes tests now covered by DBItest.

**Comment by JackStat** [comment]
So does DBItest replace all of the testthat tests?

**Comment by krlmlr** [comment]
As far as I can tell, yes.

**Comment by krlmlr** [comment]
@hadley: Can we merge this (and the corresponding PRs for the other back ends)? I have fixed the version of DBItest in .travis.yml to decouple development.

**Pull request merged**
