### PR TITLE
Convert dates

### PR DESCRIPTION
**Pull request by thrasibule**
This a tentative solution for #24. It probably would make more sense to convert the dates at the C++ level, but this works reasonably well for now.

### CODE REVIEW

**Comment by hadley** [comment]
Yeah, I'd rather do this in C++, which will require a bit of work, creating a new enum for known types (instead of using SEXPTYPE) etc.

**Comment by JackStat** [comment]
Is it possible to accept this pull request and then create a new issue for moving it into C++.  Dates are a real pain to deal with right now.

**Comment by krlmlr** [comment]
Can you install using `devtools::install("rstats-db/RPostgres#25")` for now?

**Comment by JackStat** [comment]
Yes I could but it is a year old now and a bit behind. @thrasibule can you pull and merge?

**Comment by krlmlr** [comment]
Closing in favor of #111.

**Pull request closed without merging**
