### PR TITLE
No error when JSONB is the type

### LINKED ISSUE #42: Add Postgres9.4 JSONB type.
Postgres9.4 added the JSONB type (field type: 3802). DBI/RPostgres seem to return the correct result, but there's an extra warning about the unknown field type.  

postgres [slightly official reference for field types](http://doxygen.postgresql.org/include_2catalog_2pg__type_8h.html)

```
create table test (data JSONB);
INSERT INTO test(data) values ('{"name":"mike"}');
```

```r
con <- dbConnect(RPostgres::Postgres(), dbname='testjson')
dbListTables(con)
dbGetQuery(con, "select * from test;")
dbDisconnect(con)
```

```r
              data
1 {"name": "mike"}
Warning message:
In result_create(conn@ptr, statement) :
  Unknown field type (3802) in column data
```

### PR DESCRIPTION
**Pull request by JackStat**
closes #42 and adds a test case for the issue

### CODE REVIEW

**Comment by JackStat** [comment]
Is it failing because it is using an older version of postgres (not 9.4).  All tests passed locally for me.

**Comment by robertzk** [comment]
@JackStat Yes. Try [using Postgres 9.4 in Travis](http://docs.travis-ci.com/user/using-postgresql/)

```yml
# in .travis.yaml file
addons:
  postgresql: "9.4"
```

**Comment by robertzk** [comment]
See, for example, https://github.com/rstats-db/RPostgres/pull/46 @JackStat

**Comment by coolbutuseless** [comment]
Excellent! thanks @JackStat @hadley

**Pull request merged**
