### PR TITLE
add sqlAppendTable method for PqConnection

### PR DESCRIPTION
**Pull request by r2evans**
related to (but still different from) #91, allows:

``` r
dbExecute(con, sqlAppendTable(con, tblname, dat))
```

(Used in a scenario where I need to get auto-populated via `"INSERT INTO table (...) VALUES (...) RETURNING id"`.)

### CODE REVIEW

**Comment by r2evans** [comment]
For the appveyor build, I don't understand why this error is there:

> `Project file "RPostgres.Rproj" is not a valid MSBuild project file which must be an XML.`

I didn't modify the file, and though it is certainly not xml, it is present in both branches. (I'll fix the travis error in a bit. I also have a couple of other tweaks I didn't catch before submitting.)

**Comment by krlmlr** [comment]
Thanks. I don't understand why we need to override `sqlData()` here -- `DBI::sqlData()` already seems to be generic enough. What's the behavior of RPostgres without this PR?

**Comment by krlmlr** [comment]
I got confused. So you did actually override `sqlAppendTable()`, but why is *that* necessary?

**Comment by r2evans** [comment]
I've gone back to my use-cases, and it must have been something else that was pushing me to suggest the change.

**Pull request closed without merging**
